version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    assignees:
      - "nutcas3"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    allow:
      - dependency-type: "all"
    ignore: []
    groups:
      rust-dependencies:
        patterns: ["*"]
