[package]
name = "smile_id"
version = "0.1.0"
edition = "2024"
authors = ["Nutcase <mauricee423@gmail.com>"]
description = "Rust client for Smile ID's identity verification services across Africa"
license = "MIT"

repository = "https://github.com/nutcas3/smile-id-rust"
readme = "README.md"
keywords = ["identity", "verification", "kyc", "africa", "smile-id"]
categories = ["api-bindings", "authentication"]

[dependencies]
reqwest = { version = "0.13.2", features = ["json", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
hmac = "0.13.0"
sha2 = "0.11.0"
base64 = "0.23.0"
chrono = "0.4.44"
async-trait = "0.1.89"
tokio = { version = "1.52.1", features = ["full"], optional = true }
url = "2.5.8"

[features]
default = ["async"]
async = ["tokio"]
blocking = []

[dev-dependencies]
tokio-test = "0.4.5"
mockito = "1.7.2"
